const ADDRESS_BOOK_TABS = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
  '#',
];

const CONFIG = {
  title: 'Contact Page',
  ContactPage: "Contact-Card",
  Email: 'e-mail',
  Phone: 'phone',
  Street: 'street',
  State: 'state',
  Postcode: 'postcode',
  City: 'city',
  EmailMsg: 'No Email address provided',
  PhoneMsg: 'No Phone number provided',
  StateMsg: 'No state is provided',
  StreetMsgNo: 'No number provided',
  StreetMsgName: 'No name provided',
  PostcodeMsg: 'No postcode is provided',
  CityMsg: 'No city is provided',
  userUrl: 'https://api.randomuser.me',
  numberCards: 150,
};

export { ADDRESS_BOOK_TABS, CONFIG };
